version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  hdfs:
    image: cloudera/quickstart:latest
    hostname: quickstart.cloudera
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - HIVE_OPTS="-hiveconf mapreduce.map.memory.mb=16000 -hiveconf mapreduce.reduce.memory.mb=16000"
    command: /usr/bin/docker-quickstart
    ports:
      - "80:80"
      - "7180:7180"
      - "8020:8020"
      - "8888:8888"
      - "10000:10000"
      - "50010:50010"
      - "50070:50070"
      - "50075:50075"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
